[package]
name = "semverq"
version = "0.1.0"
authors = ["eldesh <nephits@gmail.com>"]
edition = "2018"

[dependencies]
semver = "1.0.0"
thiserror = "1"
regex = "1"
clap = { version = "3.1", features = ["derive"] }
anyhow = "1.0"
serde_json = "1.0.81"
