name: check

on:
  push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        rust-version: [
          '1.54.0',
          '1.55.0',
          '1.56.0',
          '1.57.0',
          '1.58.0',
          '1.59.0',
          '1.60.0',
        ]
    name: build and test semverq
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust-version }}
          components: rustfmt, clippy, rust-docs
          override: true

      - name: format check
        run: cargo fmt -- --check

      - name: lint check
        run: cargo clippy -- -D warnings

      - name: generate documents
        run: cargo doc

      - name: run unit test
        run: cargo test -- --nocapture

      - name: build
        run: cargo build

  make-man:
    runs-on: ubuntu-18.04
    name: build manual of semverq
    steps:
      - uses: actions/checkout@v2
      - name: install prerequiresites
        run: sudo apt-get install pandoc

      - name: make manual
        run: make man

