name: check

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        rust-version: [
          '1.54.0',
          '1.55.0',
          '1.56.0',
          '1.57.0',
          '1.58.0',
          '1.59.0',
          '1.60.0',
        ]
    name: build and test semverq
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust-version }}
          components: rustfmt, clippy, rust-docs
          override: true

      - name: format check
        run: cargo fmt -- --check

      - name: lint check
        run: cargo clippy -- -D warnings

      - name: generate documents
        run: cargo doc

      - name: run unit test
        run: cargo test -- --nocapture

      - name: build
        run: cargo build

  package:
    runs-on: ubuntu-18.04
    needs: test
    env:
      DEBIAN_FRONTEND: noninteractive
    name: packaging semverq as a deb package
    steps:
      - uses: actions/checkout@v2
      - name: set environment variables
        run: cat .env >> $GITHUB_ENV
      - name: install dependencies of packaging
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends devscripts cdbs debhelper build-essential curl
      - name: packaging
        run: |
          ln -s $(pwd) $GITHUB_WORKSPACE/semverq-${{ env.DEB_VERSION }}
          cd $GITHUB_WORKSPACE/semverq-${{ env.DEB_VERSION }}
          debuild -uc -us

