name: deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - master

env:
  RUST_VERSION: 1.60.0

jobs:
  deploy:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release-v')
    runs-on: ubuntu-18.04
    name: Deploy to crates.io
    env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Packaging SemVerq
        run: cargo package

      - name: Publish the SermVerq package
        run: cargo publish

